#!/bin/bash
USERNAME="krolmiki2011"
PUSH_USERNAME="immutablearch"

set -euo pipefail

image="localhost/arch-coreos:latest"

podman build --net host --security-opt label=disable --cap-add all -f Containerfile --tag "$image" .

commit=$(podman run --rm "$image" ostree rev-parse --single)
diffid=$(podman inspect "$image" | jq -r '.[0].RootFS.Layers[-1]')

echo "FROM $image" | podman build \
    --label ostree.commit="$commit" \
    --label ostree.final-diffid="$diffid"\
    --tag "$image" -

token=$(<token.txt)
podman login ghcr.io \
  --username "$USERNAME" \
  --password "$token"

podman tag "$image" ghcr.io/"$PUSH_USERNAME"/arch-coreos:latest
podman push ghcr.io/"$PUSH_USERNAME"/arch-coreos:latest
