---
name: Build container image
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "05 10 * * *" # 10:05am UTC everyday
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:

env:
  IMAGE_DESC: "Experimental arch-coreos OSTree/Bootc Image"
  IMAGE_KEYWORDS: "bootc,archlinux,arch"
  IMAGE_NAME: "${{ github.event.repository.name }}"
  IMAGE_REGISTRY: "ghcr.io/${{ github.repository_owner }}"
  DEFAULT_TAG: "latest"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}-${{ inputs.brand_name}}-${{ inputs.stream_name }}
  cancel-in-progress: true

jobs:
  build_push:
    name: Build and push image
    runs-on: ubuntu-24.04

    container:
        image: archlinux:latest
        options: --privileged

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Arch-CoreOS
        run: |
            ./build.sh
      - name: Install Podman
        run: |
          pacman -Syu --noconfirm podman

      - name: Log in to GHCR with Podman
        env:
          GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "$GHCR_TOKEN" | podman login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Push to GHCR
        run: |
            podman load -i /tmp/image.tar
            podman tag image:latest ghcr.io/immutablearch/arch-coreos:latest
            podman push ghcr.io/immutablearch/arch-coreos:latest
