name: Build & Push Arch-coreos

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm \
            base-devel git wget curl archlinux-keyring \
            podman buildah skopeo

      - name: Log in to GHCR with Podman
        run: |
            OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
            echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u $OWNER --password-stdin


      - name: Build Arch-coreod image
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          podman build -t ghcr.io/$OWNER/arch-coreod:latest .

      - name: Push to GHCR
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          podman push ghcr.io/$OWNER/arch-coreos:latest
