name: Build Arch-CoreOS

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Podman Login
        run: |
            echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Install podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Run build script
        run: |
          chmod +x ./build
          ./build
