name: Build Arch-CoreOS Image

on:
    push:
        branches: [ "main" ]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Build arch-coreos
              run: |
                podman build \
                    -t localhost/arch-coreos:latest \
                    .

                commit=$(podman run --rm localhost/arch-coreos:latest ostree rev-parse --single)
                diffid=$(podman inspect localhost/arch-coreos:latest | jq -r '.[0].RootFS.Layers[-1]')

                echo "FROM localhost/arch-coreos:latest" | podman build \
                    --label ostree.commit="$commit" \
                    --label ostree.final-diffid="$diffid"\
                    --tag ghcr.io/immutablearch/arch-coreos:latest -

            - name: Login to GHCR
              run: |
                echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

            - name: Push to GHCR
              run: |
                podman push ghcr.io/immutablearch/arch-coreos:latest

