---
name: Build container image
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "05 10 * * *"
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:

env:
  IMAGE_DESC: "Experimental arch-coreos OSTree/Bootc Image"
  IMAGE_KEYWORDS: "bootc,archlinux,arch"
  IMAGE_NAME: "${{ github.event.repository.name }}"
  IMAGE_REGISTRY: "ghcr.io/immutablearch"
  DEFAULT_TAG: "latest"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_push:
    name: Build and push image
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y podman buildah skopeo

      - name: Build Arch-CoreOS container with Buildah
        run: |
          buildah bud -t temp -f Containerfile .
          cid=$(podman create temp)
          podman cp $cid:/tmp/image.ociarchive image.ociarchive
          podman rm $cid

      - name: Log in to GHCR with Podman
        env:
          GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "$GHCR_TOKEN" | podman login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Push to GHCR
        run: |
            skopeo copy --dest-compress-format gzip image.ociarchive docker://${IMAGE_REGISTRY}/$IMAGE_NAME:$DEFAULT_TAG
