name: Build Arch-CoreOS

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up podman
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Run build script
        run: |
          chmod +x ./build.sh
          ./build.sh
